from datetime import UTC, datetime
from typing import Any

from app.database.json_store import JsonStore
from app.models.infrastructure import InfrastructureStatus
from app.repositories.json_infrastructure_repository import JsonInfrastructureRepository


def get_seed_records() -> list[dict[str, Any]]:
    source_date = datetime(2026, 1, 1, tzinfo=UTC).isoformat()
    now = datetime.now(UTC).isoformat()

    raw_records = [
        {
            "name": "Hospital Governador Celso Ramos",
            "type": "HOSPITAL",
            "latitude": -27.58838,
            "longitude": -48.55062,
            "cep": "88015-270",
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Rua Irmã Benwarda",
            "number": "297",
            "source": "CNES/SES-SC",
            "source_updated_at": source_date,
        },
        {
            "name": "Hospital Infantil Joana de Gusmão",
            "type": "HOSPITAL",
            "latitude": -27.57671,
            "longitude": -48.53529,
            "cep": "88025-301",
            "city": "Florianópolis",
            "neighborhood": "Agronômica",
            "street": "Rua Rui Barbosa",
            "number": "152",
            "source": "CNES/SES-SC",
            "source_updated_at": source_date,
        },
        {
            "name": "Hospital Nereu Ramos",
            "type": "HOSPITAL",
            "latitude": -27.57779,
            "longitude": -48.53372,
            "cep": "88025-301",
            "city": "Florianópolis",
            "neighborhood": "Agronômica",
            "street": "Rua Rui Barbosa",
            "number": "800",
            "source": "CNES/SES-SC",
            "source_updated_at": source_date,
        },
        {
            "name": "Maternidade Carmela Dutra",
            "type": "HOSPITAL",
            "latitude": -27.58919,
            "longitude": -48.55023,
            "cep": "88015-270",
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Rua Irmã Benwarda",
            "number": "208",
            "source": "CNES/SES-SC",
            "source_updated_at": source_date,
        },
        {
            "name": "Hospital Universitário UFSC",
            "type": "HOSPITAL",
            "latitude": -27.59990,
            "longitude": -48.52060,
            "cep": "88036-800",
            "city": "Florianópolis",
            "neighborhood": "Trindade",
            "street": "Rua Profa. Maria Flora Pausewang",
            "number": "108",
            "source": "CNES/UFSC",
            "source_updated_at": source_date,
        },
        {
            "name": "Hospital Regional de São José",
            "type": "HOSPITAL",
            "latitude": -27.60966,
            "longitude": -48.63005,
            "cep": "88103-901",
            "city": "São José",
            "neighborhood": "Praia Comprida",
            "street": "Rua Adolfo Donato da Silva",
            "number": "s/n",
            "source": "CNES/SES-SC",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM Almirante Carvalhal",
            "type": "ESCOLA",
            "latitude": -27.60690,
            "longitude": -48.57709,
            "cep": "88080-150",
            "city": "Florianópolis",
            "neighborhood": "Coqueiros",
            "street": "Rua Bento Góia",
            "number": "113",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM Donícia Maria da Costa",
            "type": "ESCOLA",
            "latitude": -27.54881,
            "longitude": -48.49643,
            "cep": "88032-001",
            "city": "Florianópolis",
            "neighborhood": "Saco Grande",
            "street": "Rodovia Virgílio Várzea",
            "number": "1267",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM Batista Pereira",
            "type": "ESCOLA",
            "latitude": -27.70225,
            "longitude": -48.53634,
            "cep": "88064-000",
            "city": "Florianópolis",
            "neighborhood": "Ribeirão da Ilha",
            "street": "Rodovia Baldicero Filomeno",
            "number": "3000",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM José Amaro Cordeiro",
            "type": "ESCOLA",
            "latitude": -27.71655,
            "longitude": -48.50746,
            "cep": "88066-000",
            "city": "Florianópolis",
            "neighborhood": "Morro das Pedras",
            "street": "Rodovia Francisco Thomaz dos Santos / SC-406",
            "number": "1691",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM Virgílio dos Reis Várzea",
            "type": "ESCOLA",
            "latitude": -27.43281,
            "longitude": -48.45605,
            "cep": "88054-030",
            "city": "Florianópolis",
            "neighborhood": "Canasvieiras",
            "street": "Rua Manoel Mancellos Moura",
            "number": "100",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "EBM Luiz Cândido da Luz",
            "type": "ESCOLA",
            "latitude": -27.44882,
            "longitude": -48.43405,
            "cep": "88058-000",
            "city": "Florianópolis",
            "neighborhood": "Vargem do Bom Jesus",
            "street": "Rodovia Armando Calil Bulos",
            "number": "km 3",
            "source": "Censo Escolar/INEP",
            "source_updated_at": source_date,
        },
        {
            "name": "1ª Delegacia de Polícia da Capital",
            "type": "POLICIA_CIVIL",
            "latitude": -27.59314,
            "longitude": -48.55141,
            "cep": "88015-100",
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Av. Prefeito Osmar Cunha",
            "number": "263",
            "source": "Polícia Civil/SC",
            "source_updated_at": source_date,
        },
        {
            "name": "6ª Delegacia de Polícia da Capital",
            "type": "POLICIA_CIVIL",
            "latitude": -27.57297,
            "longitude": -48.53486,
            "cep": "88025-500",
            "city": "Florianópolis",
            "neighborhood": "Agronômica",
            "street": "Rua Delminda Silveira",
            "number": "811",
            "source": "Polícia Civil/SC",
            "source_updated_at": source_date,
        },
        {
            "name": "1ª Região de Polícia Militar",
            "type": "POLICIA_MILITAR",
            "latitude": -27.59255,
            "longitude": -48.54964,
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Rua Presidente Nereu Ramos",
            "number": "354",
            "source": "Polícia Militar/SC",
            "source_updated_at": source_date,
        },
        {
            "name": "Terminal Rodoviário Rita Maria",
            "type": "TERMINAL_RODOVIARIO",
            "latitude": -27.59716,
            "longitude": -48.55802,
            "cep": "88010-906",
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Avenida Paulo Fontes",
            "number": "1101",
            "source": "OpenStreetMap",
            "source_updated_at": source_date,
        },
        {
            "name": "Terminal de Integração do Centro — TICEN",
            "type": "TERMINAL_URBANO",
            "latitude": -27.59844,
            "longitude": -48.55346,
            "city": "Florianópolis",
            "neighborhood": "Centro",
            "street": "Avenida Paulo Fontes",
            "number": "s/n",
            "source": "OpenStreetMap",
            "source_updated_at": source_date,
        },
        {
            "name": "Aeroporto Internacional de Florianópolis — Hercílio Luz",
            "type": "AEROPORTO",
            "latitude": -27.66999,
            "longitude": -48.54730,
            "cep": "88047-900",
            "altitude_m": 5.0,
            "city": "Florianópolis",
            "neighborhood": "Carianos",
            "street": "Av. Deputado Diomício Freitas",
            "number": "3393",
            "source": "DECEA/ANAC",
            "source_updated_at": source_date,
        },
        {
            "name": "Ponte Hercílio Luz",
            "type": "PONTE",
            "latitude": -27.59389,
            "longitude": -48.56583,
            "city": "Florianópolis",
            "neighborhood": "Centro/Estreito",
            "street": "Ponte Hercílio Luz",
            "number": "s/n",
            "source": "OpenStreetMap",
            "source_updated_at": source_date,
        },
        {
            "name": "Ponte Colombo Salles",
            "type": "PONTE",
            "latitude": -27.59720,
            "longitude": -48.56530,
            "city": "Florianópolis",
            "neighborhood": "Centro/Estreito",
            "street": "Complexo de Pontes",
            "number": "s/n",
            "source": "OpenStreetMap",
            "source_updated_at": source_date,
        },
    ]

    records: list[dict[str, Any]] = []
    for raw in raw_records:
        record = JsonStore.new_record(
            {
                **raw,
                "status": InfrastructureStatus.OK.value,
                "altitude_m": raw.get("altitude_m"),
                "cep": raw.get("cep"),
            }
        )
        record["created_at"] = now
        record["updated_at"] = now
        records.append(record)

    return records


def seed_infrastructure_data(repository: JsonInfrastructureRepository | None = None) -> None:
    repo = repository or JsonInfrastructureRepository()
    if not repo.is_empty():
        return
    repo.replace_all(get_seed_records())
